# src/reasoning/query_processor.py

"""
WarehouseQueryProcessor — natural-language Q&A layer for the AtlasFlow pipeline.

Bridges the gap between the deterministic AI decision stack and the operator
by letting users ask free-form questions about the current warehouse status.
Answers are generated by the Hugging Face text-generation pipeline that is
already initialised and held in memory by the FastAPI server.

Design notes
------------
- Stateless: no mutable instance state is kept between calls.  The class is
  safe to share across threads and requires no synchronisation.

- Prompt engineering: a strict, context-injected prompt format is used so
  that flan-t5-small (an instruction-tuned model) stays grounded in the
  actual warehouse state.  Free-form generation without context would
  hallucinate facts; anchoring to ``current_status`` and ``explanation``
  keeps responses factual and brief.

- Graceful degradation: Hugging Face inference can fail for many reasons
  (OOM, tokenisation edge cases, model unavailability).  The ``answer_query``
  method wraps the call in a try/except and returns a polite fallback string
  so the server endpoint never 500s due to the language model alone.

- No torch dependency: this module is a pure Python orchestration layer.
  All tensor logic lives upstream (AtlasModel, DecisionHead, etc.).
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------
# The template is intentionally terse and imperative so that flan-t5-small
# (a relatively small model) can follow it reliably without drifting into
# unrelated topics.
#
# Slot descriptions:
#   {current_status} — e.g. "CRITICAL"
#   {explanation}    — e.g. "Highest attention on SCAN_FAILED at Aisle 4, Bin 12."
#   {query}          — the operator's free-form question

_PROMPT_TEMPLATE: str = (
    "Context: The warehouse status is {current_status}. "
    "The main issue is {explanation} "
    "Question: {query} "
    "Answer briefly and professionally:"
)

# Returned to the caller whenever HF generation fails or produces empty output.
_FALLBACK_RESPONSE: str = (
    "I'm sorry, I was unable to generate an answer at this time. "
    "Please consult the status and explanation fields for details."
)


class WarehouseQueryProcessor:
    """
    Natural-language Q&A interface for warehouse status queries.

    Accepts a free-form operator question and the current AI-generated context
    (status + explanation), constructs a grounded prompt, and delegates answer
    generation to the Hugging Face pipeline that is already resident in memory
    on the FastAPI server.

    Parameters
    ----------
    max_new_tokens : int, optional
        Maximum number of tokens the model may generate per answer.
        Keeping this small (default 50) ensures low CPU latency and
        prevents the model from rambling beyond a single concise sentence.

    Examples
    --------
    >>> processor = WarehouseQueryProcessor()
    >>> answer = processor.answer_query(
    ...     query="What is causing the delay?",
    ...     current_status="DELAY",
    ...     explanation="Highest attention on SCAN_FAILED at Aisle 4, Bin 12.",
    ...     hf_pipeline=hf_generator,
    ... )
    >>> print(answer)
    'A scan failure at Aisle 4, Bin 12 is causing the delay.'
    """

    def __init__(self, max_new_tokens: int = 50) -> None:
        if max_new_tokens < 1:
            raise ValueError(
                f"max_new_tokens must be a positive integer, got {max_new_tokens!r}"
            )
        self._max_new_tokens = max_new_tokens

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def answer_query(
        self,
        query: str,
        current_status: str,
        explanation: str,
        hf_pipeline: Any,
    ) -> str:
        """
        Generate a concise natural-language answer to an operator question.

        Parameters
        ----------
        query : str
            The operator's free-form question about the warehouse state,
            e.g. ``"What is causing the delay?"`` or
            ``"Which aisle should I inspect first?"``.
        current_status : str
            The AI's current warehouse state prediction — one of
            ``"NORMAL"``, ``"DELAY"``, or ``"CRITICAL"``.
            Injected verbatim into the prompt so the model stays grounded.
        explanation : str
            Human-readable XAI string produced by
            :class:`~src.reasoning.explainer.AttentionExplainer` or
            :class:`~src.policy.action_policy.ActionPolicy`, e.g.
            ``"Highest attention on SCAN_FAILED at Aisle 4, Bin 12 (position 3 in window)."``.
        hf_pipeline : callable
            The Hugging Face ``transformers.pipeline`` instance already
            held in server memory.  Expected call signature::

                hf_pipeline(prompt: str, max_new_tokens: int)
                    -> list[dict[str, str]]

            where each dict contains a ``"generated_text"`` key.

        Returns
        -------
        str
            A clean, stripped answer string from the language model.
            Returns :data:`_FALLBACK_RESPONSE` if generation fails or
            produces an empty result.

        Notes
        -----
        The method never raises — all exceptions from ``hf_pipeline`` are
        caught and logged so that the calling endpoint remains available.
        """
        # --- Build grounded prompt ----------------------------------------
        prompt = _PROMPT_TEMPLATE.format(
            current_status=current_status.strip(),
            explanation=explanation.strip(),
            query=query.strip(),
        )

        logger.debug("WarehouseQueryProcessor prompt: %s", prompt)

        # --- Generate answer -----------------------------------------------
        try:
            raw_output = hf_pipeline(prompt, max_new_tokens=self._max_new_tokens)

            # HF pipeline returns: list[dict], e.g. [{"generated_text": "..."}]
            generated_text: str = raw_output[0].get("generated_text", "").strip()

            if not generated_text:
                # Model returned a non-empty response list but empty text —
                # treat as a soft failure and use the fallback.
                logger.warning(
                    "HF pipeline returned empty generated_text for query: %r", query
                )
                return _FALLBACK_RESPONSE

            logger.info("Query answered: %r -> %r", query, generated_text)
            return generated_text

        except Exception as exc:  # noqa: BLE001
            # Broad catch is intentional: HF can raise OOM, tokenisation
            # errors, network errors (for API-backed models), etc.
            # Log the root cause for debugging, but keep the endpoint alive.
            logger.error(
                "HF generation failed for query %r: %s", query, exc, exc_info=True
            )
            return _FALLBACK_RESPONSE

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def build_prompt(
        self,
        query: str,
        current_status: str,
        explanation: str,
    ) -> str:
        """
        Construct the context-injected prompt string without calling the model.

        Useful for testing prompt content independently of the HF pipeline
        and for logging / audit purposes in production.

        Parameters
        ----------
        query : str
            The operator's free-form question.
        current_status : str
            Current AI-predicted warehouse state.
        explanation : str
            XAI explanation string from the upstream pipeline.

        Returns
        -------
        str
            The fully-formatted prompt that would be sent to the model.
        """
        return _PROMPT_TEMPLATE.format(
            current_status=current_status.strip(),
            explanation=explanation.strip(),
            query=query.strip(),
        )

    # ------------------------------------------------------------------
    # Dunder helpers
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"max_new_tokens={self._max_new_tokens})"
        )
